# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Climawatch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'NVActivityIndicatorView'
  # Pods for Climawatch

  target 'ClimawatchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClimawatchUITests' do
    # Pods for testing
  end

end
